version: '3'
# run with: docker-compose -f docker-compose.yml -f docker-compose-with-reloading.yml up --build
services:
    location-microservice:
        container_name: location-microservice
        volumes:
            - "./location-microservice:/usr/src/app"

    live-reloader:
        image: apogiatzis/livereloading
        container_name: livereloader
        privileged: true
        environment:
          - RELOAD_DELAY=1.5              # seconds
          - RELOAD_CONTAINER=location-microservice
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./location-microservice:/usr/src/app"
        depends_on:
            - location-microservice

    activity-microservice:
        container_name: activity-microservice
        volumes:
            - "./activity-microservice:/usr/src/app"

    live-reloader-activity:
        image: apogiatzis/livereloading
        container_name: livereloaderactivity
        privileged: true
        environment:
          - RELOAD_DELAY=1.5              # seconds
          - RELOAD_CONTAINER=activity-microservice
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
            - "./activity-microservice:/usr/src/app"
        depends_on:
            - activity-microservice
