version: '3'
services:
  user-microservice:
    image: user-microservice
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    container_name: user-microservice
    ports:
      - "3000:3000"
    depends_on:
      -   mongo-container

  mongo-container:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"

  authentication-microservice:
    image: authentication-microservice
    build: 
      context: ./authentication-microservice
      dockerfile: Dockerfile
    container_name: authentication-microservice
    ports:
      - "4000:4000"
  
  location-microservice:
    image: location-microservice
    build:
      context: ./location-microservice
      dockerfile: Dockerfile
    container_name: location-microservice
    ports:
      - "3030:3030"
    depends_on:
      -   mongo-container

  mongo-location-container:
    image: mongo
    container_name: mongo-location-container
    ports:
      - "27018:27017"

  socket-microservice:
    image: socket-microservice
    build:
      context: ./socket-microservice
      dockerfile: Dockerfile
    container_name: socket-microservice
    ports:
      - "8000:8000"


