version: '3'
services:
  user-microservice:
    image: user-microservice
    build:
      context: ./user-microservice
      dockerfile: Dockerfile
    container_name: user-microservice
    ports:
      - "3000:3000"
    depends_on:
      -   mongo-container

  mongo-container:
    image: mongo
    container_name: mongo-container
    ports:
      - "27017:27017"

  authentication-microservice:
    image: authentication-microservice
    build: 
      context: ./authentication-microservice
      dockerfile: Dockerfile
    container_name: authentication-microservice
    ports:
      - "4000:4000"
